###################################################################

# Created by write_sdc on Tue Dec  2 11:34:30 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
set_driving_cell -lib_cell INVX1 [get_ports {data_in[63]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[62]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[61]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[60]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[59]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[58]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[57]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[56]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[55]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[54]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[53]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[52]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[51]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[50]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[49]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[48]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[47]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[46]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[45]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[44]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[43]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[42]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[41]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[40]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[39]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[38]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[37]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[36]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[35]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[34]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[33]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[32]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[31]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[30]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[29]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[28]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[27]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[26]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[25]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[24]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[23]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[22]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[21]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[20]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[19]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[18]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[17]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[16]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[15]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[14]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[13]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[12]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[11]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[10]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[9]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[8]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[7]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[6]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[5]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[4]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {data_in[0]}]
set_driving_cell -lib_cell INVX1 [get_ports t_valid_in]
set_driving_cell -lib_cell INVX1 [get_ports clk]
set_driving_cell -lib_cell INVX1 [get_ports resetn]
create_clock -name vclk  -period 20  -waveform {0 10}
set_input_delay -clock vclk  1  [get_ports {data_in[63]}]
set_input_delay -clock vclk  1  [get_ports {data_in[62]}]
set_input_delay -clock vclk  1  [get_ports {data_in[61]}]
set_input_delay -clock vclk  1  [get_ports {data_in[60]}]
set_input_delay -clock vclk  1  [get_ports {data_in[59]}]
set_input_delay -clock vclk  1  [get_ports {data_in[58]}]
set_input_delay -clock vclk  1  [get_ports {data_in[57]}]
set_input_delay -clock vclk  1  [get_ports {data_in[56]}]
set_input_delay -clock vclk  1  [get_ports {data_in[55]}]
set_input_delay -clock vclk  1  [get_ports {data_in[54]}]
set_input_delay -clock vclk  1  [get_ports {data_in[53]}]
set_input_delay -clock vclk  1  [get_ports {data_in[52]}]
set_input_delay -clock vclk  1  [get_ports {data_in[51]}]
set_input_delay -clock vclk  1  [get_ports {data_in[50]}]
set_input_delay -clock vclk  1  [get_ports {data_in[49]}]
set_input_delay -clock vclk  1  [get_ports {data_in[48]}]
set_input_delay -clock vclk  1  [get_ports {data_in[47]}]
set_input_delay -clock vclk  1  [get_ports {data_in[46]}]
set_input_delay -clock vclk  1  [get_ports {data_in[45]}]
set_input_delay -clock vclk  1  [get_ports {data_in[44]}]
set_input_delay -clock vclk  1  [get_ports {data_in[43]}]
set_input_delay -clock vclk  1  [get_ports {data_in[42]}]
set_input_delay -clock vclk  1  [get_ports {data_in[41]}]
set_input_delay -clock vclk  1  [get_ports {data_in[40]}]
set_input_delay -clock vclk  1  [get_ports {data_in[39]}]
set_input_delay -clock vclk  1  [get_ports {data_in[38]}]
set_input_delay -clock vclk  1  [get_ports {data_in[37]}]
set_input_delay -clock vclk  1  [get_ports {data_in[36]}]
set_input_delay -clock vclk  1  [get_ports {data_in[35]}]
set_input_delay -clock vclk  1  [get_ports {data_in[34]}]
set_input_delay -clock vclk  1  [get_ports {data_in[33]}]
set_input_delay -clock vclk  1  [get_ports {data_in[32]}]
set_input_delay -clock vclk  1  [get_ports {data_in[31]}]
set_input_delay -clock vclk  1  [get_ports {data_in[30]}]
set_input_delay -clock vclk  1  [get_ports {data_in[29]}]
set_input_delay -clock vclk  1  [get_ports {data_in[28]}]
set_input_delay -clock vclk  1  [get_ports {data_in[27]}]
set_input_delay -clock vclk  1  [get_ports {data_in[26]}]
set_input_delay -clock vclk  1  [get_ports {data_in[25]}]
set_input_delay -clock vclk  1  [get_ports {data_in[24]}]
set_input_delay -clock vclk  1  [get_ports {data_in[23]}]
set_input_delay -clock vclk  1  [get_ports {data_in[22]}]
set_input_delay -clock vclk  1  [get_ports {data_in[21]}]
set_input_delay -clock vclk  1  [get_ports {data_in[20]}]
set_input_delay -clock vclk  1  [get_ports {data_in[19]}]
set_input_delay -clock vclk  1  [get_ports {data_in[18]}]
set_input_delay -clock vclk  1  [get_ports {data_in[17]}]
set_input_delay -clock vclk  1  [get_ports {data_in[16]}]
set_input_delay -clock vclk  1  [get_ports {data_in[15]}]
set_input_delay -clock vclk  1  [get_ports {data_in[14]}]
set_input_delay -clock vclk  1  [get_ports {data_in[13]}]
set_input_delay -clock vclk  1  [get_ports {data_in[12]}]
set_input_delay -clock vclk  1  [get_ports {data_in[11]}]
set_input_delay -clock vclk  1  [get_ports {data_in[10]}]
set_input_delay -clock vclk  1  [get_ports {data_in[9]}]
set_input_delay -clock vclk  1  [get_ports {data_in[8]}]
set_input_delay -clock vclk  1  [get_ports {data_in[7]}]
set_input_delay -clock vclk  1  [get_ports {data_in[6]}]
set_input_delay -clock vclk  1  [get_ports {data_in[5]}]
set_input_delay -clock vclk  1  [get_ports {data_in[4]}]
set_input_delay -clock vclk  1  [get_ports {data_in[3]}]
set_input_delay -clock vclk  1  [get_ports {data_in[2]}]
set_input_delay -clock vclk  1  [get_ports {data_in[1]}]
set_input_delay -clock vclk  1  [get_ports {data_in[0]}]
set_input_delay -clock vclk  1  [get_ports t_valid_in]
set_input_delay -clock vclk  1  [get_ports clk]
set_input_delay -clock vclk  1  [get_ports resetn]
set_output_delay -clock vclk  1  [get_ports t_ready]
set_output_delay -clock vclk  1  [get_ports {t_data[63]}]
set_output_delay -clock vclk  1  [get_ports {t_data[62]}]
set_output_delay -clock vclk  1  [get_ports {t_data[61]}]
set_output_delay -clock vclk  1  [get_ports {t_data[60]}]
set_output_delay -clock vclk  1  [get_ports {t_data[59]}]
set_output_delay -clock vclk  1  [get_ports {t_data[58]}]
set_output_delay -clock vclk  1  [get_ports {t_data[57]}]
set_output_delay -clock vclk  1  [get_ports {t_data[56]}]
set_output_delay -clock vclk  1  [get_ports {t_data[55]}]
set_output_delay -clock vclk  1  [get_ports {t_data[54]}]
set_output_delay -clock vclk  1  [get_ports {t_data[53]}]
set_output_delay -clock vclk  1  [get_ports {t_data[52]}]
set_output_delay -clock vclk  1  [get_ports {t_data[51]}]
set_output_delay -clock vclk  1  [get_ports {t_data[50]}]
set_output_delay -clock vclk  1  [get_ports {t_data[49]}]
set_output_delay -clock vclk  1  [get_ports {t_data[48]}]
set_output_delay -clock vclk  1  [get_ports {t_data[47]}]
set_output_delay -clock vclk  1  [get_ports {t_data[46]}]
set_output_delay -clock vclk  1  [get_ports {t_data[45]}]
set_output_delay -clock vclk  1  [get_ports {t_data[44]}]
set_output_delay -clock vclk  1  [get_ports {t_data[43]}]
set_output_delay -clock vclk  1  [get_ports {t_data[42]}]
set_output_delay -clock vclk  1  [get_ports {t_data[41]}]
set_output_delay -clock vclk  1  [get_ports {t_data[40]}]
set_output_delay -clock vclk  1  [get_ports {t_data[39]}]
set_output_delay -clock vclk  1  [get_ports {t_data[38]}]
set_output_delay -clock vclk  1  [get_ports {t_data[37]}]
set_output_delay -clock vclk  1  [get_ports {t_data[36]}]
set_output_delay -clock vclk  1  [get_ports {t_data[35]}]
set_output_delay -clock vclk  1  [get_ports {t_data[34]}]
set_output_delay -clock vclk  1  [get_ports {t_data[33]}]
set_output_delay -clock vclk  1  [get_ports {t_data[32]}]
set_output_delay -clock vclk  1  [get_ports {t_data[31]}]
set_output_delay -clock vclk  1  [get_ports {t_data[30]}]
set_output_delay -clock vclk  1  [get_ports {t_data[29]}]
set_output_delay -clock vclk  1  [get_ports {t_data[28]}]
set_output_delay -clock vclk  1  [get_ports {t_data[27]}]
set_output_delay -clock vclk  1  [get_ports {t_data[26]}]
set_output_delay -clock vclk  1  [get_ports {t_data[25]}]
set_output_delay -clock vclk  1  [get_ports {t_data[24]}]
set_output_delay -clock vclk  1  [get_ports {t_data[23]}]
set_output_delay -clock vclk  1  [get_ports {t_data[22]}]
set_output_delay -clock vclk  1  [get_ports {t_data[21]}]
set_output_delay -clock vclk  1  [get_ports {t_data[20]}]
set_output_delay -clock vclk  1  [get_ports {t_data[19]}]
set_output_delay -clock vclk  1  [get_ports {t_data[18]}]
set_output_delay -clock vclk  1  [get_ports {t_data[17]}]
set_output_delay -clock vclk  1  [get_ports {t_data[16]}]
set_output_delay -clock vclk  1  [get_ports {t_data[15]}]
set_output_delay -clock vclk  1  [get_ports {t_data[14]}]
set_output_delay -clock vclk  1  [get_ports {t_data[13]}]
set_output_delay -clock vclk  1  [get_ports {t_data[12]}]
set_output_delay -clock vclk  1  [get_ports {t_data[11]}]
set_output_delay -clock vclk  1  [get_ports {t_data[10]}]
set_output_delay -clock vclk  1  [get_ports {t_data[9]}]
set_output_delay -clock vclk  1  [get_ports {t_data[8]}]
set_output_delay -clock vclk  1  [get_ports {t_data[7]}]
set_output_delay -clock vclk  1  [get_ports {t_data[6]}]
set_output_delay -clock vclk  1  [get_ports {t_data[5]}]
set_output_delay -clock vclk  1  [get_ports {t_data[4]}]
set_output_delay -clock vclk  1  [get_ports {t_data[3]}]
set_output_delay -clock vclk  1  [get_ports {t_data[2]}]
set_output_delay -clock vclk  1  [get_ports {t_data[1]}]
set_output_delay -clock vclk  1  [get_ports {t_data[0]}]
set_output_delay -clock vclk  1  [get_ports t_valid]
set_output_delay -clock vclk  1  [get_ports t_last]
set_output_delay -clock vclk  1  [get_ports {t_keep[5]}]
set_output_delay -clock vclk  1  [get_ports {t_keep[4]}]
set_output_delay -clock vclk  1  [get_ports {t_keep[3]}]
set_output_delay -clock vclk  1  [get_ports {t_keep[2]}]
set_output_delay -clock vclk  1  [get_ports {t_keep[1]}]
set_output_delay -clock vclk  1  [get_ports {t_keep[0]}]
